hl.on("hyprland.start", function()
	hl.exec_cmd("hyprctl setcursor catppuccin-mocha-dark-cursors 20")
	-- hl.exec_cmd("hyprpm reload")

	hl.exec_cmd("~/.config/gsr/start-gsr.sh")
	hl.exec_cmd("pypr")
	hl.exec_cmd("waybar")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("wl-paste --watch cliphist store&")
end)
