exec-once = kitty -o background_opacity=0 -o background_blur=0 --class desktop-clock -- tty-clock -C 5

windowrule {
  name = desktop-clock
  match:class = ^(desktop-clock)$

  opacity = 0
  decorate = false
  float = true
  pin = true
  no_blur = true
  no_dim = true
  no_shadow = true
  no_focus = true
  no_follow_mouse = true
  rounding = 0

  size = 304 164
  move = 1568 250
}

windowrule {
  name = desktop-clock-active
  match:class = ^(desktop-clock)$
  match:workspace = w[p1] w[1]
  
  opacity = 1
  no_blur = false
}

