[mgr]
show_hidden = true
linemode = "size"

[[plugin.prepend_fetchers]]
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
url = "*/"
run = "git"
group = "git"

# Set as wallpaper in <S-o> menu
[[opener.set-wallpaper]]
run = "set-wallpaper %s1"
for = "linux"
desc = "Set as wallpaper"

[[open.prepend_rules]]
mime = "image/*"
use = ["open", "set-wallpaper"]
