[mgr]
show_hidden = true
linemode = "size"

[preview]
max_width = 2400
max_height = 3000

# Set as wallpaper in <S-o> menu
[[opener.set-wallpaper]]
run = "set-wallpaper %s1"
for = "linux"
desc = "Set as wallpaper"

[[open.prepend_rules]]
mime = "image/*"
use = ["open", "set-wallpaper"]

[plugin]
prepend_fetchers = [
  { url = "*", run = "git", group = "git" },
  { url = "*/", run = "git", group = "git" },
]
prepend_previewers = [{ mime = "audio/*", run = "exifaudio" }]
